[package]
name = "shadowaudit"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.10.1"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.63.0" }

[[target.starknet-contract]]
sierra = true
casm = true
